version: "2"
services:
  cvparser-v5-entrance:
    image: registry.cn-hangzhou.aliyuncs.com/mesoor-ai/cvparser-entrance:0.0.5a1
    restart: always
    environment:
      LOG_LEVEL: INFO
      GRPC_PORT: "19090"
      CVPARSER_FILE_URL: "cvparser-v5-file"
    command:
        - bash
        - -c
        - |
          uvicorn cvparser_entrance.http_server:app --host '0.0.0.0' --port 8080 --workers 1 &
          python cvparser_entrance/servicer/cvparser_servicer.pyc
    ports:
     - "8888:8080"

  cvparser-v5-file-kneader:
    image: registry.cn-hangzhou.aliyuncs.com/mesoor-ai/cvparse-local:file-kneader-0.2.21
    restart: always
    ports:
     - "80:9090"
    command: "bin/file-kneader -J-server -Dconfig.file=/conf/application.conf -Dlogback.configurationFile=/conf/logback.xml -J-XX:+UnlockExperimentalVMOptions -J-XX:+UserCGroupMemoryLimitForHeap"

  cvparser-v5-seg:
    image: registry.cn-hangzhou.aliyuncs.com/mesoor-ai/resume_seg:v1.2-pyc
    restart: always
    ports:
     - "8080:8080"
    command:
        - bash
        - -c
        - |
          python3 run_grpc_app.pyc

  cvparser-v5-ner:
    image: registry.cn-hangzhou.aliyuncs.com/mesoor-ai/resume_ner:v1.4-pyc
    restart: always
    command:
        - bash
        - -c
        - |
          python3 run_grpc_app.pyc
    ports:
     - "8081:8081"

  cvparser-v5-ocr:
    image: registry.cn-hangzhou.aliyuncs.com/mesoor-ai/cvparser-ocr:2.5
    restart: always
    environment:
      PORT: "8000"
    command:
        - bash
        - -c
        - |
          python server.py
    ports:
     - "5555:8000"

  cvparser-v5-file:
    image: registry.cn-hangzhou.aliyuncs.com/mesoor-ai/cvparser-file:0.0.5
    restart: always
    environment:
      FILE_KNEADER_HOST: cvparser-v5-file-kneader
      FILE_KNEADER_PORT: "80"
      FILE_KNEADER_VERSION: "v1"
      BLOCK_SEG_HOST: cvparser-v5-seg
      BLOCK_SEG_PORT: "8080"
      NER_HOST: cvparser-v5-ner
      NER_PORT: "8081"
      OCR_HOST: cvparser-v5-ocr
      OCR_PORT: "5000"
      PYTHONPATH: "./"
      EXP_MAX_HEAD_N: "5"
    command:
        - bash
        - -c
        - |
          uvicorn cvparser_file.service.http_server:app --host '0.0.0.0' --port 8080 --workers 2
    ports:
     - "8082:8080"